trigger:
 - 'master'
 
pool:
 vmImage: 'ubuntu-18.04'
 
stages:
 
- stage: Build
  displayName: 'Build Stage'
  jobs:
   - job: MaevenSetUp
     steps:
       #- task: Maven@3
       #  inputs:
       #    mavenPomFile: 'pom.xml'
       #    javaHomeOption: 'JDKVersion'
       #    jdkVersionOption: 'default'
       #    options: compile exec:java -Dexec.mainClass="HelloWorld"
       #    publishJUnitResults: false
        
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
