trigger:
- master
 
pool:
 vmImage: ubuntu-latest
 
steps:
- task: Maven@3
  inputs:
   mavenPomFile: 'pom.xml'
   mavenOptions: '-Xmx3072m'
   javaHomeOption: 'JDKVersion'
   jdkArchitectureOption: 'x64'
   publishJUnitResults: false
   goals: 'package'
   options: exec:java -Dexec.mainClass="HelloWorld.ArtifactWorld.HelloWorld"